# Generated by Django 5.0.1 on 2025-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_fileversion_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.IntegerField(default=1),
        ),
    ]
