# Generated by Django 5.0.1 on 2025-06-12 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0005_alter_fileversion_version_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
