# Generated by Django 5.0.1 on 2025-06-12 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0006_fileversion_uploaded_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_name", "version_number")},
        ),
    ]
