# Generated by Django 5.0.1 on 2025-06-12 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0007_alter_fileversion_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file_name", "version_number", "user")},
        ),
    ]
